### ISSUE TITLE
The movement of the ants with food does not erase the previous position

### ISSUE THREAD

**Issue by vojtekbalazs** [gamefest2017/ants#28]
If an ant finds food and returns to the anthill, the path does not get erased, t.m. there remains an ant with food in each step. See attached picture
![screenshot 2017-10-03_22-38-26](https://user-images.githubusercontent.com/19765106/31147968-b5bc1a42-a88b-11e7-8199-b19a2f7eb915.png)

**Comment by tiborschvartz** [comment]
fixed
