### ISSUE TITLE
Playing field does not reset between games

### ISSUE THREAD

**Issue by dr-evo** [gamefest2017/ants#55]
Build df25bfc Fix for 1/4 screen size.

Steps to reproduce:
Run multiple matches in sequence during single application run.
( in MenuMain, run multiple singleplayer/duels)

Actual result:
When running second game, state from previous game is not reset, objects (ants, food) from previous game are present in new game state.

Expected result:
Game starts on blank playing field in the same fashion as with first game.

**Comment by dr-evo** [comment]
already done as far as I know (current build  b616fc38b9a7c06584030b612e9e4ed07af86148 )
implementation of match running pulled into ProcessExecutor , done by Gabo as I recall

**Comment by The0retico** [comment]
Actual reset on the engine side was probably done by )Robert and on GUI side by other Gabo... anyway, it works now:).
