### ISSUE TITLE
Decouple match execution code from MenuMain

### ISSUE THREAD

**Issue by dr-evo** [gamefest2017/ants#57]
Unify implementation of single / duel so that it can be used in another class / called multiple times

**Comment by dr-evo** [comment]
Partially related to #55

**Comment by dr-evo** [comment]
is already fixed in current build actually b616fc38b9a7c06584030b612e9e4ed07af86148
(done by gabo as I recall - match running is done via ProcessExecutor)

**Comment by The0retico** [comment]
indeed!:)
