### ISSUE TITLE
[x] Invisible Mode not operational

### ISSUE THREAD

**Issue by A60678** [gamefest2017/ants#79]
Ak v hlavnom Tournament - Qualification Menu zaskrtnem "Invisible Mode",  neda sa mi spustit dalsia hra.

**Comment by The0retico** [comment]
Prosí motestovať v aktuálnom mastri - je dosť možné, že sa len neaktualizuje tabuľk,a peot treba potom ďalšiu hru pustiť v oviditeľnom móde a sledovať, či  sa pridajú dva výsledky hier. Lokálne mám zmenu, ktorá aktualizuje zmenu, no vyskúšal som ju len raz.

**Comment by A60678** [comment]
(Ano, testujem v mastri.) Ano, hra v pozadi bezala, ale nezaktualizovalo sa menu hned po dohrani neviditelnej hry. Toto je bug.

**Comment by dr-evo** [comment]
Issue confirmed in build cf8a2c15ecf7c786d8f4c712fec5bd4013cd62c2  , 
apparently caused by showInitMenu which is now not called from handler unless RESULT_CLOSE event occurrs - which does not occur in invisible mode it seems

**Comment by dr-evo** [comment]
fixed in build  e20ebc5
