### ISSUE TITLE
Cannot start a semi / finals rounds

### ISSUE THREAD

**Issue by A60678** [gamefest2017/ants#80]
Ak su uz odohrate vsetky kvalifikacne zapasy, neda sa startom spustit semifinale.

**Comment by The0retico** [comment]
Prosím otestovať v aktuálnom mastri - it works for me.

**Comment by A60678** [comment]
Ano, vzdy testujem v mastri. Chyba bola v tom, ze som ocakaval, ze nemusim prepinat radio box z "Qualification" na "Tournament (Semi/Finals)" po odohrati poslednej kvalifikacnej hry a pred stlacenim "Start". Ak vieme narychlo urobit logiku, ze "start" nad dokoncenou kvalifikaciou automaticky spusti turnaj, spravme, ak nie, vieme zit aj s tymto... len... v tom pripade by sme mali urobit "disable" start, ak je zvolena "kvalifikacia" a vsetky zapasy su uz odohrane. (Toto vieme urobit aj na GUI strane, bez modifikacie backend.)

**Comment by dr-evo** [comment]
fixed in build  e20ebc5
