### ISSUE TITLE
Our tournament bracket is not prepared for a draw result.

### ISSUE THREAD

**Issue by A60678** [gamefest2017/ants#81]
Prekvapilo ma, ze turnament opakuje hru, ak hra skonci remiozou (vid obrazok), toto moze sposobovat problemy, kedze pri implementacii grafu sme s tym nepocitali. Vieme naimplementovat sekundarne indexy a rozhodnut o vitazovi aj pri remize? (V opacnom pripade musime premysliet datovu strukturu grafu.)

![image](https://user-images.githubusercontent.com/32138111/31881502-fa5ea81a-b7e3-11e7-9b85-ccea02092657.png)

**Comment by A60678** [comment]
PS: Je potrebne vyskusat, ci je strom pripraveny pre tento pripad (viac teamov), ak ano, mozme nechat tak.

**Comment by dr-evo** [comment]
fixed in build  e20ebc5
